function EndUI( handles )
% Display some ending texts on a blank figure
    handles.hThank = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [200, 350, 400, 150], ...
        'String', 'Thanks for playing!', ...
        'FontSize', 30, ...
        'FontName', 'Helvetica');
    handles.hDeveloper = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [200, 290, 400, 50], ...
        'String', 'Developer: Jialiu Wang       Contact: jlwang.poincare@gmail.com', ...
        'FontSize', 9, ...
        'FontName', 'Helvetica');
    handles.hVersion = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [200, 240, 400, 50], ...
        'String', 'Black Jack      Version 1.10', ...
        'FontSize', 12, ...
        'FontName', 'Helvetica');
    handles.hFrom = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'pixels', ...
        'Position', [200, 190, 400, 20], ...
        'String', 'Pictures adapted from Internet and Windows Solitaire', ...
        'FontSize', 8, ...
        'FontName', 'Helvetica');
    handles.hQuit = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Visible', 'on', ...
        'Units', 'pixels', ...
        'Position', [360, 70, 80, 80], ...
        'String', 'Quit', ...
        'FontSize', 14, ...
        'Callback', {@Quit, handles});

    uiwait(handles.hFig);
    % Clear the figure
    tmparray = get(handles.hFig, 'Children');
    delete(tmparray(end:-1:1));
    clear tmparray;
    close(handles.hFig)

end% of function

function Quit( ~, ~, handles )
% Resume, then quit the program
    uiresume(handles.hFig);
end% of function
