function startChips = StartUI(handles)
% The first step is creating a welcome screen, let player choose how many chips he/she wants to take, and click the 'Start' button.
    % Create components on the welcome screen
    handles.hStartChips = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.35, 0.47, 0.2, 0.055], ...
        'String', '100', ...
        'BackgroundColor', [1.0, 1.0, 1.0], ...
        'FontSize', 20, ...
        'FontName', 'Helvetica');
    handles.hStartButton = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.4, 0.3, 0.2, 0.1], ...
        'String', 'Start!', ...
        'FontSize', 15, ...
        'Callback', {@StartButton, handles.hFig});
    % Give start button a callback function that can record the starting
    % chips and remove all UI components, then re-arrange the whole UI.
    handles.hWelcomeText = uicontrol(handles.hFig, ...
        'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.3, 0.6, 0.45, 0.055], ...
        'String', 'Take Your Starting Chips', ...
        'FontSize', 20, ...
        'FontName', 'Helvetica');
    % Design six buttons that can be used to modify starting chips
    handles.hStartSmallPlus = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.58, 0.5, 0.06, 0.04], ...
        'String', '+1', ...
        'FontSize', 14, ...
        'Callback', {@StartSmallPlus, handles.hStartChips});
    handles.hStartSmallMinus = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.58, 0.45, 0.06, 0.04], ...
        'String', '-1', ...
        'FontSize', 14, ...
        'Callback', {@StartSmallMinus, handles.hStartChips});
    handles.hStartBigPlus = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.66, 0.5, 0.06, 0.04], ...
        'String', '+10', ...
        'FontSize', 14, ...
        'Callback', {@StartBigPlus, handles.hStartChips});
    handles.hStartBigMinus = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.66, 0.45, 0.06, 0.04], ...
        'String', '-10', ...
        'FontSize', 14, ...
        'Callback', {@StartBigMinus, handles.hStartChips});
    handles.hStartMax = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.74, 0.5, 0.06, 0.04], ...
        'String', 'Max', ...
        'FontSize', 14, ...
        'Callback', {@StartMax, handles.hStartChips});
    handles.hStartMin = uicontrol(handles.hFig, ...
        'Style', 'pushbutton', ...
        'Units', 'normalized', ...
        'Position', [0.74, 0.45, 0.06, 0.04], ...
        'String', 'Min', ...
        'FontSize', 14, ...
        'Callback', {@StartMin, handles.hStartChips});

    uiwait(handles.hFig);
    % record the current value of starting chips
    startChips = str2double(get(handles.hStartChips, 'String'));
    % delete every UI components
    tmparray = get(handles.hFig, 'Children');
    delete(tmparray(end:-1:1));
    clear tmparray;
    % Because 'handles' is copied, not referenced here, all the fields will be automatically deleted
    %fields = {'hStartChips', 'hStartButton', 'hWelcomeText', 'hStartSmallPlus', 'hStartBigPlus', 'hStartSmallMinus', 'hStartBigMinus', 'hStartMax', 'hStartMin'};
    %handles = rmfield(handles, fields);
end

function StartSmallPlus( ~, ~, hStartChips )
    tempnum = str2double(get(hStartChips, 'String'));
    % Upper limit 1024
    if tempnum <= 1023
        tempnum = tempnum + 1;
        set(hStartChips, 'String', num2str(tempnum));
    end
end

function StartSmallMinus( ~, ~, hStartChips )
    tempnum = str2double(get(hStartChips, 'String'));
    % Lower limit 1
    if tempnum > 1
        tempnum = tempnum - 1;
        set(hStartChips, 'String', num2str(tempnum));
    end
end

function StartBigPlus( ~, ~, hStartChips )
    tempnum = str2double(get(hStartChips, 'String'));
    % Upper limit 1024
    if tempnum <= 1014
        tempnum = tempnum + 10;
        set(hStartChips, 'String', num2str(tempnum));
    end
end

function StartBigMinus( ~, ~, hStartChips )
    tempnum = str2double(get(hStartChips, 'String'));
    % Lower limit 10
    if tempnum > 10
        tempnum = tempnum - 10;
        set(hStartChips, 'String', num2str(tempnum));
    end
end

function StartMax( ~, ~, hStartChips )
    % Set to Max 1024
    set(hStartChips, 'String', num2str(1024));
end

function StartMin( ~, ~, hStartChips )
    % Set to Min 1
    set(hStartChips, 'String', num2str(1));
end

function StartButton( ~, ~, hFig )
    % The only thing start button does is uiresume
    uiresume(hFig);
end

